package(default_visibility = ["//visibility:public"])

cc_library(
    name = "error_context",
    srcs = ["error_context.cc"],
    hdrs = ["error_context.h"],
    deps = [
        "//parser:source_location",
        "@com_google_absl//absl/strings",
    ],
)