package(default_visibility = ["//visibility:public"])

cc_library(
    name = "expression_visitor",
    srcs = ["expression_visitor.cc"],
    hdrs = ["expression_visitor.h"],
    deps = [
        "//core:expression"
    ],
)

cc_library(
    name = "statement_visitor",
    srcs = ["statement_visitor.cc"],
    hdrs = ["statement_visitor.h"],
    deps = [
        "//core:statement"
    ],
)