package(default_visibility = ["//visibility:public"])

cc_library(
    name = "statement_printer",
    srcs = ["statement_printer.cc"],
    hdrs = ["statement_printer.h"],
    deps = [
        "//visitor:statement_visitor"
    ],
)